<a href="https://colab.research.google.com/github/mladbago/podstawy_sztucznej_inteligencji/blob/main/Z05_D_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn import model_selection
from sklearn import  metrics
from statsmodels.formula.api import ols

# Zadanie
Proszę pobrać dane z https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
names = ['symboling','normalized-losses','make','fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']

In [3]:
data = pd.read_csv(url, names=names, delimiter=",", na_values=["?"])
print(data.shape)

(205, 26)

In [4]:
data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

# Zadanie
Proszę usunąć kolumny, które nie są numeyczne.

In [5]:
drop_list = ['symboling','make','make','fuel-type', 'aspiration', 'num-of-doors', 
             'body-style', 'drive-wheels', 'engine-location','engine-type','num-of-cylinders','fuel-system']

In [6]:
data=data.drop(drop_list, axis=1)
data.head()

,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,NaN,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

# Zadanie
Prosze usunąć brakujące dane.

In [7]:
null_counts = data.isnull().sum()
print("Number of null values in each column:\n{}".format(null_counts))

Number of null values in each column:
normalized-losses    41
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-size           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [8]:
data=data.dropna()
data.head()

,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
6,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
8,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
10,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29,16430.0

In [9]:
data.columns  = [i.replace("-","_") for i in data.columns.values  ]

In [10]:
data.head()

,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
6,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
8,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
10,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29,16430.0

# Zadanie
Proszę nauczyć wszytkie poznane modele regresji.
Który z nich działa najlepiej?

In [11]:
auto_target = data["price"]
auto_data = data.drop(["price"],axis=1)

In [12]:
auto_data.head()

,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22
6,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25
8,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20
10,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29

In [13]:
auto_target.head()

3     13950.0
4     17450.0
6     17710.0
8     23875.0
10    16430.0
Name: price, dtype: float64

In [14]:
y=auto_target
X=auto_data

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
X_train = X[:-30]
X_test = X[-30:]
 
y_train = y[:-30]
y_test = y[-30:]

In [18]:
train=pd.DataFrame(data[:-30])
train.columns = data.columns.values
train.head()

,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
6,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
8,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
10,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29,16430.0

In [19]:
test=pd.DataFrame(data[-30:])

In [20]:
model = ols("price ~ curb_weight * width * engine_size * np.log(length) * np.log(wheel_base) * np.log(highway_mpg) * np.log(city_mpg)", data).fit()
# Print the summary
print((model.summary2()))

                                                                      Results: Ordinary least squares
===========================================================================================================================================================================
Model:                                                  OLS                                                Adj. R-squared:                                       0.982
Dependent Variable:                                     price                                              AIC:                                                  2636.1474
Date:                                                   2023-04-19 16:06                                   BIC:                                                  2909.8379
No. Observations:                                       160                                                Log-Likelihood:                                       -1229.1
Df Model:                                               88                                                 F-statistic:                                          99.34
Df Residuals:                                           71                                                 Prob (F-statistic):                                   8.94e-53
R-squared:                                              0.992                                              Scale:                                                6.2035e+05
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                         Coef.       Std.Err.      t    P>|t|      [0.025         0.975]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                                               17834.5901   16830.7109  1.0596 0.2929    -15724.8943    51394.0745
curb_weight                                                                                          -3747876.1949 1809026.1234 -2.0718 0.0419  -7354971.8351  -140780.5547
width                                                                                                 -347112.3647  913191.1056 -0.3801 0.7050  -2167963.7129  1473738.9836
curb_weight:width                                                                                       -4272.3077  391510.4819 -0.0109 0.9913   -784922.0364   776377.4211
engine_size                                                                                             22147.8972  442531.3121  0.0500 0.9602   -860234.4774   904530.2718
curb_weight:engine_size                                                                              -2785596.4401 1160416.6616 -2.4005 0.0190  -5099401.5460  -471791.3342
width:engine_size                                                                                     8180808.8756 4825820.7036  1.6952 0.0944  -1441604.3088 17803222.0599
curb_weight:width:engine_size                                                                           39617.4788   17312.2122  2.2884 0.0251      5097.9082    74137.0495
np.log(length)                                                                                         137586.0498  229131.8355  0.6005 0.5501   -319289.8539   594461.9536
curb_weight:np.log(length)                                                                            1815026.0076 1411913.5832  1.2855 0.2028  -1000249.7170  4630301.7323
width:np.log(length)                                                                                  5346134.5231 3843762.3377  1.3909 0.1686  -2318109.8961 13010378.9422
curb_weight:width:np.log(length)                                                                       -15236.2636   64565.3781 -0.2360 0.8141   -143975.9709   113503.4438
engine_size:np.log(length)                                                                             -64170.1016  592896.7112 -0.1082 0.9141  -1246372.5664  1118032.3632
curb_weight:engine_size:np.log(length)                                                                 513846.5275  222439.3928  2.3101 0.0238     70314.9756   957378.0794
width:engine_size:np.log(length)                                                                     -1648289.2442  916854.6575 -1.7978 0.0765  -3476445.5074   179867.0190
curb_weight:width:engine_size:np.log(length)                                                            -7282.1794    3288.2286 -2.2146 0.0300    -13838.7210     -725.6378
np.log(wheel_base)                                                                                     226316.8721  189111.1885  1.1967 0.2354   -150760.1278   603393.8720
curb_weight:np.log(wheel_base)                                                                         168964.8850 1291973.4364  0.1308 0.8963  -2407156.9794  2745086.7494
width:np.log(wheel_base)                                                                             -1803339.8102 4465472.3934 -0.4038 0.6875 -10707238.8716  7100559.2511
curb_weight:width:np.log(wheel_base)                                                                    11399.5137   89314.1579  0.1276 0.8988   -166687.8591   189486.8866
engine_size:np.log(wheel_base)                                                                        -732492.6149  732837.1812 -0.9995 0.3209  -2193728.4517   728743.2220
curb_weight:engine_size:np.log(wheel_base)                                                             614676.8890  248290.7865  2.4756 0.0157    119599.1221  1109754.6560
width:engine_size:np.log(wheel_base)                                                                 -1750147.7386 1051512.7149 -1.6644 0.1004  -3846804.5423   346509.0650
curb_weight:width:engine_size:np.log(wheel_base)                                                        -8755.1192    3718.1339 -2.3547 0.0213    -16168.8676    -1341.3707
np.log(length):np.log(wheel_base)                                                                     2075746.9942  628030.4736  3.3052 0.0015    823489.7969  3328004.1915
curb_weight:np.log(length):np.log(wheel_base)                                                         -267174.6676  278144.8308 -0.9606 0.3400   -821779.7081   287430.3729
width:np.log(length):np.log(wheel_base)                                                               -877471.7935 1060265.7353 -0.8276 0.4107  -2991581.6242  1236638.0371
curb_weight:width:np.log(length):np.log(wheel_base)                                                      1265.0512   14510.8974  0.0872 0.9308    -27668.8565    30198.9588
engine_size:np.log(length):np.log(wheel_base)                                                          431542.1085  241204.4258  1.7891 0.0779    -49405.8565   912490.0736
curb_weight:engine_size:np.log(length):np.log(wheel_base)                                             -113592.9778   47444.6051 -2.3942 0.0193   -208194.8335   -18991.1221
width:engine_size:np.log(length):np.log(wheel_base)                                                    349033.1237  201304.6581  1.7339 0.0873    -52356.9640   750423.2115
curb_weight:width:engine_size:np.log(length):np.log(wheel_base)                                          1612.4324     704.2382  2.2896 0.0250       208.2213     3016.6435
np.log(highway_mpg)                                                                                   -331423.9287  212377.8418 -1.5605 0.1231   -754893.3177    92045.4603
curb_weight:np.log(highway_mpg)                                                                      -3969923.2750 1806010.7402 -2.1982 0.0312  -7571006.4119  -368840.1382
width:np.log(highway_mpg)                                                                            -2006541.5645  930586.8367 -2.1562 0.0345  -3862079.0155  -151004.1136
curb_weight:width:np.log(highway_mpg)                                                                   80996.3618  150398.7275  0.5385 0.5919   -218890.1834   380882.9070
engine_size:np.log(highway_mpg)                                                                        992540.6416 1132821.1880  0.8762 0.3839  -1266240.6527  3251321.9359
curb_weight:engine_size:np.log(highway_mpg)                                                            743107.6628  372180.1150  1.9966 0.0497      1001.5910  1485213.7345
width:engine_size:np.log(highway_mpg)                                                                -1488005.8538 1693935.0479 -0.8784 0.3827  -4865616.4074  1889604.6998
curb_weight:width:engine_size:np.log(highway_mpg)                                                      -10933.3126    5605.7140 -1.9504 0.0551    -22110.7888      244.1635
np.log(length):np.log(highway_mpg)                                                                   -1630609.2236  739656.8605 -2.2045 0.0307  -3105443.1148  -155775.3323
curb_weight:np.log(length):np.log(highway_mpg)                                                         634679.9026  537358.6762  1.1811 0.2415   -436782.8658  1706142.6710
width:np.log(length):np.log(highway_mpg)                                                             -2264224.0077 1539212.4185 -1.4710 0.1457  -5333326.4006   804878.3852
curb_weight:width:np.log(length):np.log(highway_mpg)                                                   -13382.7942   25559.1533 -0.5236 0.6022    -64346.2984    37580.7101
engine_size:np.log(length):np.log(highway_mpg)                                                         383416.9330 3355525.1618  0.1143 0.9094  -6307310.2076  7074144.0736
curb_weight:engine_size:np.log(length):np.log(highway_mpg)                                            -138269.8497   70795.1788 -1.9531 0.0547   -279431.4270     2891.7276
width:engine_size:np.log(length):np.log(highway_mpg)                                                   310855.5423  297358.4296  1.0454 0.2994   -282060.3262   903771.4107
curb_weight:width:engine_size:np.log(length):np.log(highway_mpg)                                         2026.6877    1059.6739  1.9126 0.0598       -86.2419     4139.6174
np.log(wheel_base):np.log(highway_mpg)                                                                -653394.6257  620010.8407 -1.0538 0.2955  -1889661.1293   582871.8779
curb_weight:np.log(wheel_base):np.log(highway_mpg)                                                    1039127.6267  578211.9625  1.7971 0.0766   -113794.2808  2192049.5343
width:np.log(wheel_base):np.log(highway_mpg)                                                          1114893.6768 1275548.2297  0.8741 0.3850  -1428477.2555  3658264.6092
curb_weight:width:np.log(wheel_base):np.log(highway_mpg)                                               -20467.8349   33923.2864 -0.6034 0.5482    -88108.9468    47173.2770
engine_size:np.log(wheel_base):np.log(highway_mpg)                                                     792681.0081 2413207.3715  0.3285 0.7435  -4019117.8246  5604479.8408
curb_weight:engine_size:np.log(wheel_base):np.log(highway_mpg)                                        -164045.5000   79116.1872 -2.0735 0.0418   -321798.6966    -6292.3033
width:engine_size:np.log(wheel_base):np.log(highway_mpg)                                               299547.1543  353998.6479  0.8462 0.4003   -406306.1018  1005400.4104
curb_weight:width:engine_size:np.log(wheel_base):np.log(highway_mpg)                                     2416.9875    1193.9053  2.0244 0.0467        36.4080     4797.5671
np.log(length):np.log(wheel_base):np.log(highway_mpg)                                                -2920749.5653 2316642.9391 -1.2608 0.2115  -7540004.3885  1698505.2579
curb_weight:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                     -172011.2116  128448.2928 -1.3391 0.1848   -428129.8331    84107.4100
width:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                            426457.9014  374100.2569  1.1400 0.2581   -319476.8247  1172392.6274
curb_weight:width:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                  3457.5467    5755.8281  0.6007 0.5500     -8019.2485    14934.3419
engine_size:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                     -331727.2854 1042135.3105 -0.3183 0.7512  -2409686.0757  1746231.5049
curb_weight:engine_size:np.log(length):np.log(wheel_base):np.log(highway_mpg)                           30570.8435   15000.3126  2.0380 0.0453       661.0698    60480.6173
width:engine_size:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                -62254.8310   62863.3715 -0.9903 0.3254   -187600.8337    63091.1717
curb_weight:width:engine_size:np.log(length):np.log(wheel_base):np.log(highway_mpg)                      -448.7515     225.0613 -1.9939 0.0500      -897.5110        0.0080
np.log(city_mpg)                                                                                        79342.7194  193658.6995  0.4097 0.6833   -306801.7599   465487.1988
curb_weight:np.log(city_mpg)                                                                         -6810212.2433 3310475.2038 -2.0572 0.0433 -13411112.3189  -209312.1677
width:np.log(city_mpg)                                                                               -1877117.5829  890591.6699 -2.1077 0.0386  -3652906.9362  -101328.2296
curb_weight:width:np.log(city_mpg)                                                                     116049.6086  138791.6165  0.8361 0.4059   -160693.0145   392792.2318
engine_size:np.log(city_mpg)                                                                          -675681.6542 1808264.0235 -0.3737 0.7098  -4281257.7105  2929894.4021
curb_weight:engine_size:np.log(city_mpg)                                                              1115418.7835  371341.7084  3.0038 0.0037    374984.4471  1855853.1200
width:engine_size:np.log(city_mpg)                                                                   -3428523.7075 1310236.9529 -2.6167 0.0108  -6041061.9895  -815985.4255
curb_weight:width:engine_size:np.log(city_mpg)                                                         -15575.9087    5443.5079 -2.8614 0.0055    -26429.9552    -4721.8623
np.log(length):np.log(city_mpg)                                                                        598465.5199  794952.3447  0.7528 0.4540   -986624.4352  2183555.4750
curb_weight:np.log(length):np.log(city_mpg)                                                            579979.9161  696869.6244  0.8323 0.4081   -809538.6495  1969498.4817
width:np.log(length):np.log(city_mpg)                                                                  126062.2838 1259514.5948  0.1001 0.9206  -2385338.4887  2637463.0564
curb_weight:width:np.log(length):np.log(city_mpg)                                                      -11935.8209   23091.4965 -0.5169 0.6068    -57978.9572    34107.3154
engine_size:np.log(length):np.log(city_mpg)                                                          -2714700.0848 3510812.1271 -0.7732 0.4419  -9715060.6399  4285660.4702
curb_weight:engine_size:np.log(length):np.log(city_mpg)                                               -203262.0631   71310.2602 -2.8504 0.0057   -345450.6835   -61073.4426
width:engine_size:np.log(length):np.log(city_mpg)                                                      709394.7502  266394.6266  2.6629 0.0096    178218.9513  1240570.5491
curb_weight:width:engine_size:np.log(length):np.log(city_mpg)                                            2829.5187    1031.6865  2.7426 0.0077       772.3942     4886.6431
np.log(wheel_base):np.log(city_mpg)                                                                   1248349.1466  585774.2046  2.1311 0.0365     80348.5565  2416349.7368
curb_weight:np.log(wheel_base):np.log(city_mpg)                                                       1804963.9302 1108993.7218  1.6276 0.1080   -406306.7459  4016234.6062
width:np.log(wheel_base):np.log(city_mpg)                                                              588344.8232 2042195.8394  0.2881 0.7741  -3483678.0258  4660367.6722
curb_weight:width:np.log(wheel_base):np.log(city_mpg)                                                  -30270.0387   34088.3095 -0.8880 0.3775    -98240.1974    37700.1200
engine_size:np.log(wheel_base):np.log(city_mpg)                                                      -3024034.5449 2513460.2673 -1.2031 0.2329  -8035731.9743  1987662.8845
curb_weight:engine_size:np.log(wheel_base):np.log(city_mpg)                                           -246007.2768   80098.5015 -3.0713 0.0030   -405719.1527   -86295.4009
width:engine_size:np.log(wheel_base):np.log(city_mpg)                                                  796684.6161  300725.7169  2.6492 0.0099    197054.5674  1396314.6648
curb_weight:width:engine_size:np.log(wheel_base):np.log(city_mpg)                                        3437.9581    1181.6338  2.9095 0.0048      1081.8472     5794.0690
np.log(length):np.log(wheel_base):np.log(city_mpg)                                                    7219308.3739 2899515.8370  2.4898 0.0151   1437838.0021 13000778.7458
curb_weight:np.log(length):np.log(wheel_base):np.log(city_mpg)                                        -192220.5113  190355.7997 -1.0098 0.3160   -571779.1956   187338.1729
width:np.log(length):np.log(wheel_base):np.log(city_mpg)                                              -164098.4605  299206.6649 -0.5484 0.5851   -760699.6054   432502.6845
curb_weight:width:np.log(length):np.log(wheel_base):np.log(city_mpg)                                     3616.4435    5668.9145  0.6379 0.5256     -7687.0511    14919.9380
engine_size:np.log(length):np.log(wheel_base):np.log(city_mpg)                                        1049190.3892 1195584.9262  0.8776 0.3831  -1334738.2446  3433119.0230
curb_weight:engine_size:np.log(length):np.log(wheel_base):np.log(city_mpg)                              44929.3043   15325.6940  2.9316 0.0045     14370.7384    75487.8703
width:engine_size:np.log(length):np.log(wheel_base):np.log(city_mpg)                                  -161915.0321   62023.2741 -2.6106 0.0110   -285585.9282   -38244.1361
curb_weight:width:engine_size:np.log(length):np.log(wheel_base):np.log(city_mpg)                         -626.0250     223.2694 -2.8039 0.0065     -1071.2115     -180.8384
np.log(highway_mpg):np.log(city_mpg)                                                                  -192764.2287  696835.6716 -0.2766 0.7829  -1582215.0942  1196686.6368
curb_weight:np.log(highway_mpg):np.log(city_mpg)                                                      3432537.7690 1631137.6681  2.1044 0.0389    180141.6343  6684933.9037
width:np.log(highway_mpg):np.log(city_mpg)                                                            -664081.6218 1369422.8906 -0.4849 0.6292  -3394633.3118  2066470.0681
curb_weight:width:np.log(highway_mpg):np.log(city_mpg)                                                 -55978.4537   50856.9048 -1.1007 0.2747   -157384.2417    45427.3344
engine_size:np.log(highway_mpg):np.log(city_mpg)                                                      3563326.7046 3291241.7030  1.0827 0.2826  -2999222.8596 10125876.2689
curb_weight:engine_size:np.log(highway_mpg):np.log(city_mpg)                                          -304944.8115  110173.5118 -2.7679 0.0072   -524624.5546   -85265.0683
width:engine_size:np.log(highway_mpg):np.log(city_mpg)                                                 689971.9190  409082.0185  1.6866 0.0961   -125714.4585  1505658.2965
curb_weight:width:engine_size:np.log(highway_mpg):np.log(city_mpg)                                       4357.9151    1665.7457  2.6162 0.0109      1036.5125     7679.3178

In [21]:
from sklearn import  metrics
metrics.r2_score(train.price, model.predict(train))

0.991502917071331

In [22]:
from sklearn import  metrics
metrics.r2_score(test.price, model.predict(test))

0.9929112963309058

In [23]:
X_train
X_test 
y_train
y_test

170    11199.0
171    11549.0
172    17669.0
173     8948.0
174    10698.0
175     9988.0
176    10898.0
177    11248.0
178    16558.0
179    15998.0
180    15690.0
182     7775.0
183     7975.0
184     7995.0
185     8195.0
186     8495.0
187     9495.0
188     9995.0
190     9980.0
194    12940.0
195    13415.0
196    15985.0
197    16515.0
198    18420.0
199    18950.0
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, dtype: float64

In [24]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn import model_selection
from sklearn import datasets, linear_model

In [27]:
seed=123
kfold = model_selection.KFold(n_splits=10, random_state=seed)

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(make_pipeline(PolynomialFeatures(degree=2), linear_model.LinearRegression()),
                    param_grid={'polynomialfeatures__degree': [1, 2, 3, 4, 5]},
                    cv=kfold,
                    refit=True)
#make_pipeline(PolynomialFeatures(degree=2), linear_model.LinearRegression()).get_params().keys()
grid.fit(X_train, y_train)
print(grid.best_params_)
print(grid.best_estimator_)

ValueError: ignored

In [26]:
from sklearn import  metrics
metrics.r2_score(y_test , grid.best_estimator_.predict(X_test))

NameError: ignored